function json(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8" } }); }
function parseCookie(cookieHeader = "") { const out = {}; for (const part of cookieHeader.split(";")) { const [k, ...v] = part.trim().split("="); if (!k) continue; out[k] = v.join("="); } return out; }
async function checkSession(request, env) { const cookies = parseCookie(request.headers.get("cookie") || ""); const token = cookies.vera_session; if (!token) return false; const raw = await env.AUTH_KV.get(`session:${token}`); return !!raw; }
function normalizeText(value = "") { return String(value || "").trim(); }
function normalizeColor(value, fallback) { const str = String(value || "").trim(); return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(str) ? str : fallback; }
function normalizeNumber(value, fallback, min, max) { const num = Number(value); if (!Number.isFinite(num)) return fallback; return Math.min(max, Math.max(min, num)); }
function normalizeMode(value) { return value === "code" ? "code" : "standard"; }
function normalizeStatus(value) { return value === "published" ? "published" : "draft"; }
function normalizeTemplate(value) { return ["default", "landing", "content", "contact"].includes(value) ? value : "default"; }
function normalizeSection(section = {}, index = 0) { return { id: normalizeText(section.id) || `section-${Date.now()}-${index}`, type: ["content", "hero", "html"].includes(section.type) ? section.type : "content", title: normalizeText(section.title), content: String(section.content || ""), width: normalizeNumber(section.width, 100, 30, 100), background: normalizeColor(section.background, "#ffffff"), textColor: normalizeColor(section.textColor, "#0f172a"), padding: normalizeNumber(section.padding, 24, 0, 120), radius: normalizeNumber(section.radius, 18, 0, 60) }; }
function defaultSettings(input = {}) { return { pageBg: normalizeColor(input.pageBg, "#f8fafc"), contentBg: normalizeColor(input.contentBg, "#ffffff"), textColor: normalizeColor(input.textColor, "#0f172a"), mutedColor: normalizeColor(input.mutedColor, "#475569"), accentColor: normalizeColor(input.accentColor, "#2563eb"), buttonColor: normalizeColor(input.buttonColor, "#2563eb"), buttonTextColor: normalizeColor(input.buttonTextColor, "#ffffff"), maxWidth: normalizeNumber(input.maxWidth, 1280, 640, 2400), contentWidth: normalizeNumber(input.contentWidth, 100, 30, 100), fullWidth: !!input.fullWidth, textAlign: ["left", "center", "right"].includes(input.textAlign) ? input.textAlign : "left", borderRadius: normalizeNumber(input.borderRadius, 18, 0, 60), containerPadding: normalizeNumber(input.containerPadding, 24, 0, 120), sectionGap: normalizeNumber(input.sectionGap, 18, 0, 120), titleSize: normalizeNumber(input.titleSize, 40, 16, 120), bodySize: normalizeNumber(input.bodySize, 17, 12, 40), fullPageCode: !!input.fullPageCode }; }
function normalizePage(body = {}, previous = {}) { const mode = normalizeMode(body.mode || previous.mode); const sectionsInput = Array.isArray(body.sections) ? body.sections : Array.isArray(previous.sections) ? previous.sections : []; return { title: normalizeText(body.title || previous.title), slug: normalizeText(body.slug || previous.slug), status: normalizeStatus(body.status || previous.status), template: normalizeTemplate(body.template || previous.template), excerpt: normalizeText(body.excerpt || previous.excerpt), seoTitle: normalizeText(body.seoTitle || previous.seoTitle), seoDescription: normalizeText(body.seoDescription || previous.seoDescription), mode, content: String(body.content ?? previous.content ?? ""), html: String(body.html ?? previous.html ?? ""), css: String(body.css ?? previous.css ?? ""), js: String(body.js ?? previous.js ?? ""), sections: sectionsInput.map((section, index) => normalizeSection(section, index)), settings: defaultSettings(body.settings || previous.settings || {}), updatedAt: new Date().toISOString() }; }
function sortPages(pages = []) { return pages.slice().sort((a, b) => String(a.title || "").localeCompare(String(b.title || ""), "tr")); }
export async function onRequest(context) { const { request, env } = context; const kv = env.AUTH_KV; const slug = normalizeText(new URL(request.url).searchParams.get("slug")); if (request.method === "GET") { const pages = (await kv.get("pages", { type: "json" })) || []; if (slug) return json({ ok: true, page: pages.find((p) => p.slug === slug) || null }); return json({ ok: true, pages: sortPages(pages) }); } if (!await checkSession(request, env)) return json({ ok: false, error: "Yetkisiz" }, 401); if (request.method === "POST") { let body; try { body = await request.json(); } catch { return json({ ok: false, error: "Geçersiz istek" }, 400); } let pages = (await kv.get("pages", { type: "json" })) || []; const inputSlug = normalizeText(body.slug); const index = pages.findIndex((p) => p.slug === inputSlug); const previous = index >= 0 ? pages[index] : {}; const cleanPage = normalizePage(body, previous); if (!cleanPage.title || !cleanPage.slug) return json({ ok: false, error: "Başlık ve slug gereklidir." }, 400); const duplicate = pages.find((p, i) => p.slug === cleanPage.slug && i !== index); if (duplicate) return json({ ok: false, error: "Bu slug zaten kullanılıyor." }, 400); if (index >= 0) pages[index] = { ...previous, ...cleanPage }; else pages.push({ ...cleanPage, createdAt: new Date().toISOString() }); await kv.put("pages", JSON.stringify(pages)); return json({ ok: true, pages: sortPages(pages) }); } if (request.method === "DELETE") { let pages = (await kv.get("pages", { type: "json" })) || []; pages = pages.filter((p) => p.slug !== slug); await kv.put("pages", JSON.stringify(pages)); let menus = (await kv.get("menu", { type: "json" })) || []; menus = menus.filter((m) => m.pageSlug !== slug).map((m, index) => ({ ...m, order: index })); await kv.put("menu", JSON.stringify(menus)); return json({ ok: true, pages: sortPages(pages) }); } return json({ ok: false, error: "Geçersiz metod" }, 405); }
